# Generated by Django 2.2.3 on 2020-09-21 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0020_auto_20200910_1120'),
        ('wiki', '0003_auto_20200921_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.Project', verbose_name='关联项目'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ops', '运维文档'), ('proj', '项目文档')], max_length=20, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='wiki.Tag', verbose_name='标签'),
        ),
    ]
