# Generated by Django 2.2.3 on 2020-09-21 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_auto_20200921_1022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
