# Generated by Django 2.2.3 on 2020-09-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_auto_20200921_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
    ]
