# Generated by Django 2.2.3 on 2020-09-03 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(help_text='端口号')),
                ('protocol', models.CharField(blank=True, choices=[('T', 'TCP'), ('H', 'HTTP'), ('S', 'HTTPS'), ('D', 'DUBBO')], default='T', help_text='选择端口协议', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='请输入项目名', max_length=200)),
                ('mx_version', models.CharField(blank=True, help_text='5.2.2', max_length=8, null=True)),
                ('cp_addr', models.CharField(blank=True, help_text='管理后台地址,请以https://或http://开头', max_length=200, null=True)),
                ('cp_admin', models.CharField(blank=True, default='admin', help_text='管理后台管理员账号', max_length=50, null=True)),
                ('cp_password', models.CharField(blank=True, default='12345678', help_text='管理后台管理员密码', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='1.1.1.1', help_text='服务器ip')),
                ('env', models.CharField(choices=[('prod', '生产环境'), ('uat', '联调环境'), ('dev', '开发环境'), ('test', '测试环境')], default='pord', max_length=100)),
                ('root', models.CharField(blank=True, default='root', help_text='服务器账号', max_length=200)),
                ('passwd', models.CharField(blank=True, help_text='服务器密码', max_length=400)),
                ('remote_port', models.IntegerField(blank=True, default=22, help_text='远程端口:22,3386等')),
                ('cpu', models.IntegerField(blank=True, help_text='服务器核数', null=True)),
                ('mem', models.IntegerField(blank=True, help_text='内存,单位G', null=True)),
                ('disk', models.IntegerField(blank=True, help_text='磁盘,单位G', null=True)),
                ('os', models.CharField(blank=True, help_text='系统版本,如centos7;windows server 2016等', max_length=50)),
                ('mac', models.CharField(blank=True, help_text='物理地址', max_length=50)),
                ('os_type', models.CharField(choices=[('l', 'linux'), ('w', 'windows')], default='l', help_text='系统类型', max_length=50)),
                ('remark', models.TextField(blank=True, help_text='服务器备注', max_length=400)),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='mx-base,mx-apps,ima,msg,zk,es,etc...', max_length=100)),
                ('db_root', models.CharField(blank=True, help_text='数据库才需要填写,多个账号请用";"分隔', max_length=100)),
                ('db_passwd', models.CharField(blank=True, help_text='与数据库账号一一对应,请用";"分隔', max_length=100)),
                ('service_version', models.CharField(blank=True, help_text='5.2.2', max_length=8)),
                ('charcater', models.CharField(blank=True, choices=[('S', '单节点'), ('M', '主节点'), ('SA', '从节点'), ('A', '仲裁'), ('DU', '双节点')], default='S', help_text='节点角色', max_length=50)),
                ('remark', models.TextField(blank=True, help_text='应用备注', max_length=400)),
                ('port', models.ManyToManyField(to='cmdb.Port')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Server')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_projs', models.ManyToManyField(to='cmdb.Project')),
                ('user_name', models.OneToOneField(help_text='注意:选超级管理员的话,配置不生效', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
