# Generated by Django 2.2.3 on 2020-09-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='env',
        ),
        migrations.AddField(
            model_name='project',
            name='env',
            field=models.CharField(choices=[('prod', '生产环境'), ('uat', '联调环境'), ('dev', '开发环境'), ('test', '测试环境')], default='pord', max_length=100),
        ),
    ]
