# Generated by Django 2.2.3 on 2020-09-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20200903_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='monitor_addr',
            field=models.CharField(blank=True, help_text='监控平台地址', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='monitor_admin',
            field=models.CharField(blank=True, help_text='监控平台账号', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='cp_password',
            field=models.CharField(blank=True, help_text='监控平台密码', max_length=100, null=True),
        ),
    ]
