# Generated by Django 2.2.3 on 2020-09-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20200903_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='monitor_password',
            field=models.CharField(blank=True, help_text='监控平台密码', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='cp_password',
            field=models.CharField(blank=True, default='12345678', help_text='管理后台管理员密码', max_length=100, null=True),
        ),
    ]
