# Generated by Django 2.2.3 on 2020-09-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20200903_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mx_version',
            field=models.CharField(blank=True, choices=[('4.0', '4.0'), ('5.0', '5.0')], help_text='大版本', max_length=8, null=True),
        ),
    ]
