# Generated by Django 2.2.3 on 2020-09-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20200903_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='repl_name',
            field=models.CharField(blank=True, help_text='集群名', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='monitor_admin',
            field=models.CharField(blank=True, default='admin', help_text='监控平台账号', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='monitor_password',
            field=models.CharField(blank=True, default='MeiXin@2020', help_text='监控平台密码', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='remote_port',
            field=models.IntegerField(blank=True, default=22, help_text='远程端口:22,3389等'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_version',
            field=models.CharField(blank=True, help_text='5.2.2', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='port',
            unique_together={('protocol', 'port')},
        ),
    ]
