# Generated by Django 2.2.3 on 2020-09-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20200907_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='remark',
        ),
        migrations.AlterField(
            model_name='server',
            name='remark',
            field=models.TextField(blank=True, help_text='备注', max_length=400),
        ),
    ]
