# Generated by Django 2.2.3 on 2020-09-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_service_protocol_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='remark',
            field=models.TextField(blank=True, help_text='备注,可注明定制模块功能', max_length=400),
        ),
    ]
