# Generated by Django 2.2.3 on 2020-09-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0010_service_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='protocol_port',
        ),
    ]
