# Generated by Django 2.2.3 on 2020-09-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0012_service_protocol_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='port',
        ),
    ]
