# Generated by Django 2.2.3 on 2020-09-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0013_remove_service_port'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Port',
        ),
        migrations.AlterField(
            model_name='server',
            name='remark',
            field=models.TextField(blank=True, help_text='备注', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='remark',
            field=models.TextField(blank=True, help_text='备注,可注明定制模块功能', max_length=400, null=True),
        ),
    ]
