# Generated by Django 2.2.3 on 2020-09-09 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0014_auto_20200909_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='os',
            field=models.CharField(blank=True, help_text='系统版本,如centos7;windows server 2016等', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='passwd',
            field=models.CharField(blank=True, help_text='服务器密码', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Project'),
        ),
        migrations.AlterField(
            model_name='server',
            name='remote_port',
            field=models.IntegerField(blank=True, default=22, help_text='远程端口:22,3389等', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='charcater',
            field=models.CharField(blank=True, choices=[('S', '单节点'), ('M', '主节点'), ('SA', '从节点'), ('A', '仲裁'), ('DU', '双节点')], default='S', help_text='节点角色', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='db_passwd',
            field=models.CharField(blank=True, help_text='与数据库账号一一对应,请用";"分隔', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='db_root',
            field=models.CharField(blank=True, help_text='数据库才需要填写,多个账号请用";"分隔', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='repl_name',
            field=models.CharField(blank=True, help_text='集群名', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_version',
            field=models.CharField(blank=True, help_text='5.2.2', max_length=30, null=True),
        ),
    ]
