# Generated by Django 2.2.3 on 2020-09-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0016_auto_20200909_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目名'},
        ),
        migrations.AlterField(
            model_name='service',
            name='db_passwd',
            field=models.CharField(blank=True, help_text='与数据库账号一一对应,请用"/"分隔', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='db_root',
            field=models.CharField(blank=True, help_text='数据库才需要填写,多个账号请用"/"分隔', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='protocol_port',
            field=models.CharField(blank=True, help_text='请输入协议和端口,"-"连接,例如"TCP-8080",多个协议端口请用"/"分割', max_length=100),
        ),
    ]
