# Generated by Django 2.2.3 on 2020-09-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0017_auto_20200910_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterField(
            model_name='project',
            name='cp_addr',
            field=models.CharField(blank=True, help_text='请以https://或http://开头', max_length=200, null=True, verbose_name='管理后台地址'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cp_admin',
            field=models.CharField(blank=True, default='admin', max_length=50, null=True, verbose_name='管理后台管理员账号'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cp_password',
            field=models.CharField(blank=True, default='12345678', max_length=100, null=True, verbose_name='管理后台管理员密码'),
        ),
        migrations.AlterField(
            model_name='project',
            name='env',
            field=models.CharField(choices=[('prod', '生产环境'), ('uat', '联调环境'), ('dev', '开发环境'), ('test', '测试环境')], default='pord', max_length=100, verbose_name='环境'),
        ),
        migrations.AlterField(
            model_name='project',
            name='monitor_addr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='监控平台地址'),
        ),
        migrations.AlterField(
            model_name='project',
            name='monitor_admin',
            field=models.CharField(blank=True, default='admin', max_length=50, null=True, verbose_name='监控平台账号'),
        ),
        migrations.AlterField(
            model_name='project',
            name='monitor_password',
            field=models.CharField(blank=True, default='MeiXin@2020', max_length=100, null=True, verbose_name='监控平台密码'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mx_version',
            field=models.CharField(blank=True, choices=[('4.0', '4.0'), ('5.0', '5.0')], help_text='大版本', max_length=8, null=True, verbose_name='大版本'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, verbose_name='项目名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ops_admin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='运维全景图测试账号'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ops_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='运维全景图测试账号密码'),
        ),
    ]
