# Generated by Django 2.2.3 on 2020-09-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0018_auto_20200910_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='cpu',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU核数'),
        ),
        migrations.AlterField(
            model_name='server',
            name='disk',
            field=models.IntegerField(blank=True, null=True, verbose_name='磁盘,单位G'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.GenericIPAddressField(default='1.1.1.1', verbose_name='服务器ip'),
        ),
        migrations.AlterField(
            model_name='server',
            name='mac',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='物理地址'),
        ),
        migrations.AlterField(
            model_name='server',
            name='mem',
            field=models.IntegerField(blank=True, null=True, verbose_name='内存,单位G'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os',
            field=models.CharField(blank=True, help_text='如centos7;windows server 2016等', max_length=50, null=True, verbose_name='系统版本'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_type',
            field=models.CharField(choices=[('l', 'linux'), ('w', 'windows')], default='l', max_length=50, verbose_name='系统类型'),
        ),
        migrations.AlterField(
            model_name='server',
            name='passwd',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='服务器密码'),
        ),
        migrations.AlterField(
            model_name='server',
            name='remark',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='server',
            name='remote_port',
            field=models.IntegerField(blank=True, default=22, help_text='22,3389等', null=True, verbose_name='远程端口'),
        ),
        migrations.AlterField(
            model_name='server',
            name='root',
            field=models.CharField(blank=True, default='root', max_length=200, verbose_name='服务器账号'),
        ),
        migrations.AlterField(
            model_name='service',
            name='charcater',
            field=models.CharField(blank=True, choices=[('S', '单节点'), ('M', '主节点'), ('SA', '从节点'), ('A', '仲裁'), ('DU', '双节点')], default='S', max_length=50, null=True, verbose_name='节点角色'),
        ),
        migrations.AlterField(
            model_name='service',
            name='db_passwd',
            field=models.CharField(blank=True, help_text='与数据库账号一一对应,请用"/"分隔', max_length=100, null=True, verbose_name='数据库密码'),
        ),
        migrations.AlterField(
            model_name='service',
            name='db_root',
            field=models.CharField(blank=True, help_text='数据库才需要填写,多个账号请用"/"分隔', max_length=100, null=True, verbose_name='数据库账号'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='mx-base,mx-apps,ima,msg,zk,es,etc...', max_length=100, verbose_name='应用名'),
        ),
        migrations.AlterField(
            model_name='service',
            name='protocol_port',
            field=models.CharField(blank=True, help_text='请输入协议和端口,"-"连接,例如"TCP-8080",多个协议端口请用"/"分割', max_length=100, verbose_name='协议-端口'),
        ),
        migrations.AlterField(
            model_name='service',
            name='remark',
            field=models.TextField(blank=True, help_text='可用于注明定制模块功能或其他信息', max_length=400, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='service',
            name='repl_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='集群名'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_version',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='应用版本号'),
        ),
    ]
