# Generated by Django 2.2.3 on 2020-09-10 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0019_auto_20200910_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Project', verbose_name='关联项目'),
        ),
        migrations.AlterField(
            model_name='service',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Server', verbose_name='关联服务器'),
        ),
    ]
