# Generated by Django 2.2.3 on 2020-09-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0020_auto_20200910_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='root',
            field=models.CharField(blank=True, default='root', max_length=200, null=True, verbose_name='服务器账号'),
        ),
    ]
