# Generated by Django 2.2.3 on 2020-09-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0021_auto_20200929_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='protocol_port',
            field=models.CharField(blank=True, help_text='请输入协议和端口,"-"连接,例如"TCP-8080",多个协议端口请用"/"分割', max_length=100, null=True, verbose_name='协议-端口'),
        ),
    ]
