# Generated by Django 2.2.3 on 2020-10-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0022_auto_20200929_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='remark',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='备注'),
        ),
    ]
