"""
Django settings for mxcmdb project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@uxcot!mv3=&suz0%t+3l!5=ld_(uxw14%h^yuc8up6=3bck5g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'haystack', #搜索
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pure_pagination', #分页
    'django_crontab',
    'bootstrap3',
    'mdeditor', #md富文本编辑器
    'cmdb',
    'users', #登录登出
    'file',
    'wiki',
    'analyzer',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mxcmdb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        'libraries':{
            "wiki_tags": "wiki.templatetags.wiki_tags",
            },
        },
    },
]

WSGI_APPLICATION = 'mxcmdb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

#DATABASES = {
#   'default': {
#       'ENGINE': 'django.db.backends.sqlite3',
#       'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#   }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ["MYSQL_DB_NAME"],
        'USER': os.environ["MYSQL_ROOT"],
        'PASSWORD': os.environ["MYSQL_PASSWD"],
        'HOST': os.environ["MYSQL_HOST"],
        'PORT': os.environ["MYSQL_PORT"],
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

STATICFILES_DIRS = [
    os.path.join(BASE_DIR,"static")
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

#STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

#LOGIN_REDIRECT_URL = '/'

# session 设置
SESSION_COOKIE_AGE = 60 * 60 * 8 # 8小时
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True # 关闭浏览器，则COOKIE失效

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

#分页
PAGINATION_SETTINGS = {
    'PAGE_RANGE_DISPLAYED': 4,
    'MARGIN_PAGES_DISPLAYED': 2,
    'SHOW_FIRST_PAGE_WHEN_INVALID': True,
}

#influxdb配置
INFLUXDB = {
    'HOST': os.environ["INFLUXDB_HOST"],
    'PORT': os.environ["INFLUXDB_PORT"],
    'DATABASE': os.environ["INFLUXDB_DB_NAME"],
    'USER': os.environ["INFLUXDB_USER"],
    'PASSWD': os.environ["INFLUXDB_PASSWD"],
    }

#定时任务
CRONJOBS_LOGS_DIR = os.path.join(BASE_DIR, 'crontab_logs')
CRONJOBS = [
    ('0 * * * *', 'analyzer.get_cnt_data.get_cnt', '>> {}'.format(CRONJOBS_LOGS_DIR + '/get_cnt.log'))
]
#es search
HAYSTACK_CONNECTIONS = {
    'default': {
        #'ENGINE': 'haystack.backends.elasticsearch5_backend.Elasticsearch5SearchEngine',
        'ENGINE': 'wiki.elasticsearch5_ik_backend.Elasticsearch5IkSearchEngine',
        'URL': os.environ["ES_URL"],
        'PATH': os.path.join(BASE_DIR, 'wiki_index'),
        'INDEX_NAME': 'mxcmdb_wiki_index',
    },
}
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 2
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

#自定义高亮类
HAYSTACK_CUSTOM_HIGHLIGHTER = 'wiki.utils.Highlighter'

#自定义cdn地址
BOOTSTRAP3 = {
    "css_url": {
        "url": "https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css",
    },
    "javascript_url": {
        "url": "https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/js/bootstrap.min.js",
    },
}
